version: "3.8"

services:
    backend:
        build: ./backend
        ports:
            - "8080:8080"
        environment:
            - REDIS_HOST=host.docker.internal
            - REDIS_PORT=6379
        networks:
            - app_network

    frontend:
        build: ./frontend
        ports:
            - "3000:80"
        depends_on:
            - backend
        networks:
            - app_network

    python-job:
        build: ./jobs
        environment:
            - REDIS_HOST=host.docker.internal
            - REDIS_PORT=6379
        depends_on:
            - backend
        networks:
            - app_network

networks:
    app_network:
        driver: bridge
